name: Publish to PyPI

on:
  push:
    tags: ['v*']         # runs only on version tags

permissions:
  id-token: write        # for OIDC ➜ PyPI
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          python -m pip install --upgrade build hatchling
          python -m build

      # --- First stop: TestPyPI ---
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
          verbose: true

      # --- Manual approval gate (recommended) ---
      - name: Await prod approval
        if: github.ref_type == 'tag'
        uses: softprops/turnstyle@v1   # simple "wait for approve" action
        with:
          poll-interval-seconds: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- Second stop: production PyPI ---
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          skip_existing: true
          verbose: true 